name: Cross-Platform Compatibility Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]  # Must be quoted strings
      fail-fast: false  # Continue other tests if one fails

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ contains(matrix.os, 'macos') && 'arm64' || 'x64' }}

      - name: Install system dependencies
        run: |
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            sudo apt-get update
            sudo apt-get install -y libgl1 libgtk-3-0
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            brew install cmake
          fi

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            pip install pywin32
          fi

      - name: Run in headless mode
        run: |
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            export DISPLAY=:99
            Xvfb :99 -screen 0 1024x768x16 &
          fi
          python VirtualGestureAirCanvas.py --headless

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.os }}-py${{ matrix.python-version }}
          path: |
            test_logs/
            *.log
