name: Cross-Platform Compatibility Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.os == 'macos-latest' && 'arm64' || 'x64' }}

      # Install system dependencies per OS
      - name: Install system dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1 libgtk-3-0

      - name: Install system dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install cmake

      # Check requirements.txt
      - name: Verify requirements.txt exists
        run: |
          if [ ! -f "requirements/requirements.txt" ]; then
            echo "::error::requirements.txt not found!"
            exit 1
          fi

      # Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements.txt

      - name: Install Windows-specific Python dependencies
        if: runner.os == 'Windows'
        run: pip install pywin32

      # Run tests
      - name: Run tests
        run: |
          echo "Running tests on $RUNNER_OS"
          if [ "$RUNNER_OS" = "Linux" ]; then
            export DISPLAY=:99
            Xvfb :99 -screen 0 1024x768x16 &
          fi
          python VirtualGestureAirCanvas.py --headless
        shell: bash

      # Upload logs and test outputs (optional)
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.os }}-py${{ matrix.python-version }}
          path: |
            test_logs/
            *.log
