name: Cross-Platform Compatibility Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.os == 'macos-latest' && 'arm64' || 'x64' }}

      - name: Install system dependencies
        shell: bash
        run: |
          if [ "$RUNNER_OS" = "Linux" ]; then
            sudo apt-get update
            sudo apt-get install -y libgl1 libgtk-3-0
          elif [ "$RUNNER_OS" = "macOS" ]; then
            brew install cmake
          fi

      - name: Verify requirements.txt exists
        run: |
          if [ ! -f "requirements/requirements.txt" ]; then
            echo "::error::requirements.txt not found!"
            exit 1
          fi

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements.txt
          if [ "$RUNNER_OS" = "Windows" ]; then
            pip install pywin32
          fi

      - name: Run tests
        shell: bash
        run: |
          if [ "$RUNNER_OS" = "Linux" ]; then
            export DISPLAY=:99
            Xvfb :99 -screen 0 1024x768x16 &
          fi
          python VirtualGestureAirCanvas.py --headless

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.os }}-py${{ matrix.python-version }}
          path: |
            test_logs/
            *.log
